on:
  push:
  release:
    types: [released]

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [arm64, amd64]
    steps:
    - uses: actions/checkout@v3
    - name: build
      run: tar -czf module.tar.gz run.sh requirements.txt src
    - uses: viamrobotics/upload-module@v1
      # if: github.event_name == 'release' # <-- once the action is working, uncomment this so you only upload on release
      with:
        module-path: module.tar.gz
        org-id: 96b696a0-51b9-403b-ae0d-63753923652f # <-- replace with your org ID. not required for public modules
        platform: linux/${{ matrix.platform }}
        version: ${{ github.event_name == 'release' && github.ref_name || format('0.0.0-{0}.{1}', github.ref_name, github.run_number) }} # <-- see 'Versioning' section below for explanation
        key-id: ${{ secrets.viam_key_id }}
        key-value: ${{ secrets.viam_key_value }}
